global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: app
    basic_auth:
      username: prometheus
      password: "12345678"
    static_configs:
      - targets:
          - localhost:8080

rule_files:
  - alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
